# Generated by Django 3.0.4 on 2020-03-14 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_players_count', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(limit_value=2)])),
                ('age_restriction', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(limit_value=7)])),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy '), (2, 'Normal'), (3, 'Difficult'), (4, 'Hard'), (5, 'Extreme'), (6, 'INSANE')], default=1)),
                ('rng_factor', models.IntegerField(choices=[(1, 'Not relevant'), (2, 'Review'), (3, 'Maybe relevant'), (4, 'Relevant'), (5, 'Leading candidate')], default=1)),
                ('genre', models.IntegerField(choices=[(1, 'Board game'), (2, 'Card game'), (3, 'Deck building'), (4, 'Roleplaying game')], default=1)),
            ],
        ),
    ]
